### ISSUE TITLE
Golem RSS feed UTF-8 issues

### ISSUE THREAD

**Issue by tobyS** [kore/Torii2#7]
![image](https://user-images.githubusercontent.com/187140/202697002-34aabd2d-f038-4ebe-83df-8ab2670439fd.png)
https://rss.golem.de/rss.php?feed=RSS1.0
[feed_full-RSS1.0.zip](https://github.com/kore/portalific/files/10040934/feed_full-RSS1.0.zip)

**Comment by kore** [comment]
Fixed by letting the proxy convert the response to UTF-8
